/*
 * This source file was generated by the Gradle 'init' task
 */
package com.nukesz.tinyhttp;

public class Main {

    public static void main(String[] args) {
        System.out.println("Server is running...");
    }
}
